node {
    def rtMaven

    stage ('Clone') {
        git url: 'https://github.com/jfrog/project-examples.git'
    }

    stage ('Exec Maven') {
        docker.image('maven:3.6.1-jdk-8-slim').inside {
            withEnv(['JAVA_HOME=/usr/local/openjdk-8']) { // Java home of the container
                sh 'mvn clean install -f maven-example/pom.xml'
            }
        }
    }
}
